# Install dependencies only when needed
FROM alpine:latest

WORKDIR /dev

COPY package*.json .
RUN npm Install
COPY * .
RUN npm run build
RUN npm run export


EXPOSE 3000

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry.
# ENV NEXT_TELEMETRY_DISABLED 1

CMD ["yarn", "start"]